import type { NextPage } from 'next'
import Head from 'next/head'
import WalletConnect from '../components/WalletConnect'
import Link from 'next/link'
import Raffle from '../components/Raffle'
import { FormHero } from '../components/FormHero'
import { StartRaffle } from '../components/StartRaffle'
import { StartRaffle2 } from '../components/StartRaffle2'

const Home: NextPage = () => {

  return (
    <div>
      <Head>
        <title>Cardano Raffle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-base-100 flex justify-between mx-5 my-5 px-5 items-center">
        <div className='flex'>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
            <path strokeLinecap="round" strokeLinejoin="round" d="M16.5 6v.75m0 3v.75m0 3v.75m0 3V18m-9-5.25h5.25M7.5 15h3M3.375 5.25c-.621 0-1.125.504-1.125 1.125v3.026a2.999 2.999 0 010 5.198v3.026c0 .621.504 1.125 1.125 1.125h17.25c.621 0 1.125-.504 1.125-1.125v-3.026a2.999 2.999 0 010-5.198V6.375c0-.621-.504-1.125-1.125-1.125H3.375z" />
          </svg>

        </div>
        <div className="flex">
          <WalletConnect />
        </div>
      </div>

      {/* <div className='flex flex-col justify-center items-center'>
        <div className='flex gap-2'>
          <a href='#item1' className='btn'>test1</a>
          <a href='#item2' className='btn'>test2</a>
          <a href='#item3' className='btn'>test3</a>
        </div>

        <div className='carousel carousel-center'>
          <div id='item1' className='carousel-item justify-center w-full'>

          </div>
          <div id='item2' className='carousel-item justify-center w-full'>
            <h1>item2</h1>
          </div>
          <div id='item3' className='carousel-item justify-center w-full'>
            <h1>item3</h1>
          </div>
        </div>
      </div> */}
      
      <Raffle />


    </div>
  )
}

export default Home
