import type { NextPage } from 'next'
import Head from 'next/head'
import WalletConnect from '../components/WalletConnect'
import { useStoreActions, useStoreState } from "../utils/store"
import Link from 'next/link'
import { useState, useEffect } from 'react'
import { getAssets } from "../utils/cardano";
import initLucid from '../utils/lucid'
import Raffle from '../components/Raffle'

const Home: NextPage = () => {
  const walletStore = useStoreState((state: any) => state.wallet)
  const [nftList, setNftList] = useState([])

  useEffect(() => {
    //const lucid = initLucid(walletStore.name)
    if (walletStore.address != "") {
      // getAssets(walletStore.address)
      //   .then((res: any) => { setNftList(res.addressInfo.nfts) })
    }
  }, [walletStore.address])

  return (
    <div className="px-10">
      <Head>
        <title>Cardano Raffle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="navbar bg-base-100">
        <div className="flex-1">
          <Link href="/" className="btn btn-ghost normal-case text-xl">Raffle</Link>
        </div>
        <div className="flex-none">
          <WalletConnect />
        </div>
      </div>
      <div className="mx-40 my-10">
        <Raffle />
      </div>
    </div>
  )
}

export default Home
